function customToolBarButton(cn)

buttn1 = cn; %get the component name

[but, widID] = mlapptools.getWebElements(buttn1);       
[childbut] = mlapptools.getChildNodeIDs(but, widID);
% mlapptools.setStyle(but,'all','initial',childbut);
mlapptools.setStyle(but,'border','none',childbut);
mlapptools.setStyle(but,'box-shadow','none',childbut);
mlapptools.setStyle(but,'border-radius','0px',childbut);
mlapptools.setStyle(but,'border','none',childbut);

% cssText = [...  %get the css code to apply the custom property to dock button
%   '''<style>\n', ...
%   '  .buttn1 {\n', ...
%   '    box-sizing: border-box;\n', ...    
%   '    border: none;\n', ...   
%   '    background: none;\n', ... 
%   '    font-family: Helvetica;\n', ...     
%   '    font-weight: normal;\n', ...    
%   '    font-size: 10px;\n', ...  
%   '  }\n', ...
%   '  /* Handle on hover */\n', ...
%   '  .buttn1:hover {\n', ...   
%   '    all: unset;\n', ...     
%   '    box-sizing: border-box;\n', ...     
%   '    border: 1.1px solid rgb(180,180,180);\n', ...    
%   '    background: rgba(240,240,240,0.5);\n', ...   
%   '    font-family: Helvetica;\n', ...     
%   '    font-weight: normal;\n', ...    
%   '    font-size: 10px;\n', ...  
%   '  }\n', ...              
%   '  .buttn1:active {\n', ...  
%   '    all: initial;\n', ...       
%   '    border: 1.1px solid rgb(150,150,150);\n', ... 
%   '    background: rgba(220,220,220,0.6);\n', ... 
%   '  .buttn1:focus {\n', ...  
%   '    all: initial;\n', ...       
%   '    border: 1.85px solid rgb(130,215,245);\n', ... 
%   '    background: rgba(25,215,255,0.6);\n', ...   
%   '  }\n', ...
%   '</style>''' ...
%   ];
% 
% ww = mlapptools.getWebWindow(fig); %get web window
% ww.executeJS(['document.head.innerHTML += ',cssText]); %inject css string text
% [webwin, butIDs] = mlapptools.getWebElements(buttn1); % get the uipanel data-tag attr.
% setClassString = sprintf('dojo.addClass(dojo.query("[%s = ''%s'']")[0], "%s")',...
%                          butIDs.ID_attr, butIDs.ID_val, 'buttn1');
% webwin.executeJS(setClassString); %execute string

end
% 
