function CustomQuickMenuButton(fig,cn)

buttn2 = cn; %get the component name

[but, widID] = mlapptools.getWebElements(buttn2);       
[childbut] = mlapptools.getChildNodeIDs(but, widID);
% mlapptools.setStyle(but,'all','initial',childbut);
% mlapptools.setStyle(but,'box-shadow','none',childbut);
% mlapptools.setStyle(but,'border-radius','0px',childbut);
% mlapptools.setStyle(but,'border','0.7px solid rgb(255,255,255)',childbut);
% mlapptools.setStyle(but,'border-bottom','1.8px solid rgb(100,100,100)',childbut);
% mlapptools.setStyle(but,'border-right','1.8px solid rgb(100,100,100)',childbut);
cssText = [...  %get the css code to apply the custom property to dock button
  '''<style>\n', ...
  '  .buttn2 {\n', ...
  '    box-sizing: border-box;\n', ...    
  '    border: none;\n', ...   
  '    background: rgb(150,150,150);\n', ... 
  '    font-family: Helvetica;\n', ...     
  '    font-weight: normal;\n', ...    
  '    font-size: 10px;\n', ...  
  '    border-radius: 5px;\n', ...  
  '  }\n', ...
  '  /* Handle on hover */\n', ...
  '  .buttn2:hover {\n', ...   
  '    all: unset;\n', ...     
  '    box-sizing: border-box;\n', ...     
  '    border: 1.1px solid rgb(180,180,180);\n', ...    
  '    background: rgba(240,240,240,0.5);\n', ...   
  '    font-family: Helvetica;\n', ...     
  '    font-weight: normal;\n', ...    
  '    font-size: 10px;\n', ...  
  '  }\n', ...              
  '  .buttn2:active {\n', ...       
  '    border: 1.1px solid rgb(150,150,150);\n', ... 
  '    background: rgba(220,220,220,0.6);\n', ... 
  '  .buttn2:focus {\n', ...       
  '    border: 1.85px solid rgb(130,215,245);\n', ... 
  '    background: rgba(25,215,255,0.6);\n', ...   
  '  }\n', ...
  '</style>''' ...
  ];

ww = mlapptools.getWebWindow(fig); %get web window
ww.executeJS(['document.head.innerHTML += ',cssText]); %inject css string text
[webwin, butIDs] = mlapptools.getWebElements(buttn2); % get the uipanel data-tag attr.
setClassString = sprintf('dojo.addClass(dojo.query("[%s = ''%s'']")[0], "%s")',...
                         butIDs.ID_attr, butIDs.ID_val, 'buttn2');
webwin.executeJS(setClassString); %execute string

end
% 
